#!/usr/bin/bash

set -ex

compgen -G "${BUILDROOT}/usr/lib/extension-release.d/extension-release.*" || exit 1
compgen -G "${BUILDROOT}/usr/lib/extension-release.d/extension-release.*_*" || exit 0

for release in "${BUILDROOT}/usr/lib/extension-release.d/"extension-release.*_*
do
  cp "$release" "${release%_*}"
done

# cp /usr/lib/extension-release.d/extension-release.nca-caddy-svc_0  /usr/lib/extension-release.d/extension-release.nca-caddy-svc