#!/usr/bin/env bash

set -eux -o pipefail

setup_cosign() {

  echo "Setting up cosign ..."

  #LATEST_VERSION=$(curl https://api.github.com/repos/sigstore/cosign/releases/latest | grep tag_name | cut -d : -f2 | tr -d "v\", ")
  VERSION=2.5.2
  ARCH=amd64
  grep -i id /usr/lib/os-release
  if true #grep 'ID=fedora' /usr/lib/os-release
  then
    curl -O -L "https://github.com/sigstore/cosign/releases/download/v${VERSION}/cosign-${VERSION}-1.x86_64.rpm" #> cosign.rpm
    echo "c0a7b99f77a91452c76609c2773bae748177fcb3856c0e75df4cba5a7c0a58a4  cosign-${VERSION}-1.x86_64.rpm" | sha256sum -c
    rpm -ivh cosign-"${VERSION}"-1.x86_64.rpm
  else
    curl -O -L "https://github.com/sigstore/cosign/releases/download/v${VERSION}/cosign_${VERSION}_${ARCH}.deb"
    echo "c78b3b162ed251c76ccd6e9c801481e396ae6ebf2a82cf6ccfcc66a48020dc95 cosign_${VERSION}_${ARCH}.deb" | sha256sum -c
    dpkg -i cosign_${VERSION}_${ARCH}.deb
  fi

  echo "Done."
}

setup_xcaddy() {
  echo "Setting up xcaddy ..."

  go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
  #curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/gpg.key' | gpg --dearmor -o /tmp/caddy-xcaddy-archive-keyring.gpg
  #rpm --import /tmp/caddy-xcaddy-archive-keyring.gpg
  #curl -1sLf 'https://dl.cloudsmith.io/public/caddy/xcaddy/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-xcaddy.list
  #apt-get update
  #apt-get install -y --no-install-recommends xcaddy

  echo "Done."
}

GO_VERSION=1.25.0

setup_golang() {
  wget "https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz" -O "${ARTIFACTDIR}/go.tar.gz"
  tar -C "${BUILDROOT}/usr/local/" -xzf "${ARTIFACTDIR}/go.tar.gz"
  echo "GO INSTALLED"
  sleep 120
}

if [[ "$1" == "final" ]]
then
  setup_cosign
#  setup_golang
else
  echo "toolstree prepare script run with other args than 'final'!"
  # setup_xcaddy
fi

#if [[ "$1" == "build" ]]
#then
#  setup_xcaddy_repo
#fi
