[Config]
Dependencies=
    01-base

[Output]
Format=portable
Overlay=false
ManifestFormat=json
Output=nca-web_%v
CompressOutput=false

[Content]
Bootable=false
WithRecommends=false
WithDocs=false
CleanPackageMetadata=true
Timezone=UTC
Locale=C.UTF-8

BaseTrees=
    %O/01-base
