[Match]
Profiles=debug

[Config]
Dependencies=
    01-base
    02-incus
    03-podman
    04-ncatomic-base
    10-debug

[Content]
BaseTrees=
    %O/01-base
    %O/02-incus
    %O/03-podman
    %O/04-ncatomic-base
    %O/10-debug
