[Config]
Dependencies=
    01-base

[Output]
Format=sysext
Overlay=true
ManifestFormat=json
Output=nca-web-svc

[Content]
Bootable=false
WithRecommends=false
WithDocs=false
CleanPackageMetadata=yes
Timezone=UTC
Locale=C.UTF-8

BaseTrees=
    %O/01-base
