[Config]
Dependencies=
    01-base

[Output]
#Format=directory
Format=portable
Overlay=false
ManifestFormat=json
Output=test-svc

[Content]
Bootable=false
WithRecommends=false
WithDocs=false
CleanPackageMetadata=yes
Timezone=UTC
Locale=C.UTF-8
#BuildPackages=golang

BaseTrees=
    %O/01-base

