[Config]
Dependencies=
    20-final

[Build]
Environment=CONFEXTS=
Environment=SYSEXTS=/work/src/_mnt/mkosi.output/ncatomic.raw
Environment=SERVICE_IMAGES=
#SERVICE_IMAGES=/work/src/_mnt/mkosi.output/nca-web.raw

[Output]
Format=directory
Overlay=false
ManifestFormat=json
#ImageVersion=

[Content]
BaseTrees=
    %O/20-final
ExtraTrees=
    %C/../../../overlays/mkosi.output/ncatomic.raw:/usr/share/embedded/extensions/ncatomic_%v.raw
    %C/../../../overlays/mkosi.output/nc-aio.raw:/usr/share/embedded/extensions/nc-aio_%v.raw
    %C/../../../overlays/mkosi.output/nca-web-svc.raw:/usr/share/embedded/svc-extensions/nca-web-svc_%v.raw
    %C/../../../overlays/mkosi.output/nca-caddy-svc.raw:/usr/share/embedded/svc-extensions/nca-caddy-svc_%v.raw
    %C/../../../overlays/mkosi.output/nc-aio-svc.raw:/usr/share/embedded/svc-extensions/nc-aio-svc_%v.raw
