[Include]
Include=mkosi-tools

[Distribution]
Distribution=debian
Release=trixie

[Content]
PrepareScripts=
  %C/scripts/prepare
  %C/scripts/prepare.chroot
#BuildScripts=
#  %C/scripts/build
Packages=
    go
    yq
    python3-pyyaml
    gnupg2
#BuildPackages=go
#  cosign
