[Build]

[Config]
Dependencies=
    01-base
    # 02-podman

[Output]
Format=sysext
Overlay=true
ManifestFormat=json
Output=nc-aio-svc

[Content]
Bootable=false
WithRecommends=false
WithDocs=false
CleanPackageMetadata=yes
RemoveFiles=
    /usr/src
Timezone=UTC
Locale=C.UTF-8

# Packages=
# 	podman
# 	podman-compose
# 	catatonit
# 	passt
# 	aardvark-dns
# 	nftables

BaseTrees=
    %O/01-base
#     %O/02-podman
