[Match]
Profiles=caddy-svc

[Config]
PrepareScripts=
    scripts/caddy.prepare
BuildScripts=
    scripts/caddy.build

[Content]
ExtraTrees=
    caddy.extra
Packages=
    libsystemd-dev
RemoveFiles=
    /usr/src
