[Config]
Dependencies=01-base

[Output]
Format=sysext
Overlay=true
ManifestFormat=json
# Required so mkosi uses the correct name for sysext metadata
Output=ncatomic

[Content]
WithRecommends=false
WithDocs=false
CleanPackageMetadata=yes
RemoveFiles=/usr/src
Timezone=UTC
Locale=C.UTF-8
BaseTrees=
    %O/01-base