[Include]
Include=%C/../mkosi.common/base.conf

[Config]
Profiles=caddy-svc,nca-web-svc,nc-aio-svc,ncatomic-ext,nc-aio-ext

[Build]
BuildSources=
  .buildcache:buildcache
  %C/../src/caddy:caddy
  %C/../src/core:nca-core

[Output]
ImageId=NextcloudAtomicOverlays
Format=directory
OutputDirectory=./mkosi.output
SplitArtifacts=true

[Content]
BaseTrees=%O/01-base # Dummy base tree, we're only interested in the sub images
