[Build]
History=true
ToolsTree=%C/../tools/tools
#ToolsTreePackages=
#    yq
#    python3-pyyaml
#    golang
CacheDirectory=%C/../mkosi.cache

[Distribution]
Distribution=debian
Release=trixie
Architecture=x86-64
Repositories=non-free-firmware

