[Include]
Include=%C/../mkosi.common/base.conf

[Build]
# BuildSources=
    # .:/
    # %O:_mnt/mkosi.output
    # %C/../src/caddy:caddy
    # %C/../src/core:nca-core
    # mkosi.build-dependencies:build.dependencies
Environment=BUILD_DEPENDENCIES=/work/src/build.dependencies
Environment=BUILD_INCUS=no
Environment=PACKAGE_OCI=no
Environment=MOUNTABLE_CREDENTIALS=no
Environment=FETCH_UPSTREAM=yes
Environment=AIO_VERSION=v11.2.1
Environment=AIO_IMAGE_TAG=20250701_092737

[Config]
PassEnvironment=AIO_VERSION AIO_IMAGE_TAG FETCH_UPSTREAM

[Output]
ImageId=NextcloudAtomic
#Output=ncaio
Format=disk
OutputDirectory=mkosi.output
SplitArtifacts=true

[Validation]
SecureBoot=true
SecureBootAutoEnroll=true
SecureBootSignTool=auto
SecureBootKey=./mkosi.key
SecureBootCertificate=./mkosi.crt
SignExpectedPcr=true
VerityKey=./mkosi.key
VerityCertificate=./mkosi.crt

[Content]
Bootable=true
BaseTrees=%O/99-merged_%v
UnifiedKernelImages=true
UnifiedKernelImageFormat=%i_%v
KernelCommandLine=rw console=ttyS0 iommu=pt apparmor=0 systemd.journald.forward_to_console=1 console=ttyS0,38400
KernelModulesInitrd=true
KernelModulesInitrdExclude=.*
KernelModulesInitrdInclude=default

[Runtime]
RAM=4G
TPM=true
RuntimeSize=18G
Machine=ncatomic-test
Console=native
RuntimeTrees=mkosi.runtime:/host
Ephemeral=true
QemuArgs=-blockdev driver=raw,node-name=podmancache,discard=unmap,file.driver=file,file.filename=mkosi.podmancache,file.aio=io_uring,cache.direct=on,cache.no-flush=on -device virtio-blk-pci,drive=podmancache
KernelCommandLineExtra=-smbios type=11,value=io.systemd.stub.kernel-cmdline-extra=systemd.mount-extra=LABEL=podmancache:/podman-cache:ext4 -smbios type=11,value=io.systemd.boot.kernel-cmdline-extra=systemd.mount-extra=LABEL=podmancache:/podman-cache:ext4

#Credentials=
#    ncatomic.nextcloud.domain=nextcloudatomic.local
#    ncatomic.nextcloud.admin_password=admin