[Include]
Include=%C/../mkosi.common/base.conf

[Config]
Profiles=caddy-svc,nca-web-svc,nc-aio-svc

[Build]
#ToolsTree=default
#ToolsTreeDistribution=debian
#ToolsTreeRelease=testing

BuildSources=
  .buildcache:buildcache
  %C/../src/caddy:caddy
  %C/../src/core:nca-core

[Output]
ImageId=NextcloudAtomicPortables
Format=none
OutputDirectory=%C/mkosi.output
SplitArtifacts=true

[Validation]
SignExpectedPcr=true
VerityKey=%C/../mkosi.key
VerityCertificate=%C/../mkosi.crt

#[Content]
#BaseTrees=%O/01-base # Dummy base tree, we're only interested in the sub images

