[Match]
Profiles=test


[Content]
Packages=
    wget
    curl
    openssh-server
    openssl
    iproute2
    iputils-ping
    bind9-host
    bash-completion
    vim
    less
BuildPackages=
    gcc
    make
    ca-certificates

