[Include]
Include=
    mkosi-tools
    mkosi-vm
    mkosi-initrd

[Distribution]
#Distribution=debian
#Release=trixie
#Repositories=non-free-firmware
#Distribution=fedora

[Content]
PrepareScripts=
  %C/scripts/prepare
  %C/scripts/prepare.chroot
#BuildScripts=
#  %C/scripts/build
Packages=
    golang
    yq
    python3-yaml
    zstd
    btrfs-progs
    qemu-system-x86
    jq
    # Fedora packages
    debian-keyring
    apt
    qemu-system-x86
    qemu-system-x86-core
    qemu-kvm
    openssh
    virtiofsd
    swtpm-tools
RemovePackages=
#BuildPackages=go
#  cosign

[Build]
CacheDirectory=%C/../mkosi.cache
ToolsTree=default
ToolsTreeDistribution=debian
ToolsTreeRelease=trixie

[Output]
ImageId=tools
Format=directory
Output=tools
OutputDirectory=%C


