[Include]
Include=%C/../mkosi.common/base.conf

[Config]
Profiles=ncatomic-ext,nc-aio-ext
PassEnvironment=AIO_VERSION AIO_IMAGE_TAG FETCH_UPSTREAM

[Build]
BuildSources=
  .buildcache:buildcache
  %C/../src/core:nca-core
  %C/mkosi.images/11-ncatomic-sysext:ncatomic-sysext
Environment=FETCH_UPSTREAM=yes
Environment=AIO_VERSION=v12.5.0
Environment=AIO_IMAGE_TAG=auto

[Output]
ImageId=NextcloudAtomicSysexts
Format=none
OutputDirectory=%C/mkosi.output
SplitArtifacts=true

#[Content]
#BaseTrees=%O/01-base # Dummy base tree, we're only interested in the sub images

[Validation]
SignExpectedPcr=true
VerityKey=%C/../mkosi.key
VerityCertificate=%C/../mkosi.crt
