[Include]
Include=%C/../mkosi.common/base.conf

[Config]
Profiles=ncatomic-ext,nc-aio-ext

[Build]
BuildSources=
  .buildcache:buildcache
  %C/../src/core:nca-core

[Output]
ImageId=NextcloudAtomicSysexts
Format=none
OutputDirectory=%C/mkosi.output
SplitArtifacts=true

#[Content]
#BaseTrees=%O/01-base # Dummy base tree, we're only interested in the sub images

[Validation]
SignExpectedPcr=true
VerityKey=%C/../mkosi.key
VerityCertificate=%C/../mkosi.crt
