[Match]
Profiles=caddy

[Config]

[Content]
ExtraTrees=
    caddy.extra
Packages=
    libsystemd-dev
RemoveFiles=
    /usr/src
PrepareScripts=
    scripts/caddy.prepare
BuildScripts=
    scripts/caddy.build
PostInstallationScripts=
    scripts/caddy.postinst
